import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import QuizOption from '@/components/quizOption'
import { useEffect } from 'react'
import { useRouter } from 'next/router'


export default function Home() {

  const router = useRouter();



  useEffect( () => {
    setTimeout(() => {
      router.push('/bitches')
    }, 3000)
  }, [] )

  return (
    <>
      <Head>
        <title>Соловьев или Гитлер</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" /> 
        <link rel="preconnect" href="https://fonts.gstatic.com" /> 
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.mainTitle}><span>Соловьев</span> или <span>Гитлер</span>?</h1>
        <p className={styles.mainDescription}>Проверьте свою интуицию с помощью простой игры, в которой вам нужно угадать кому принадлежит предложенная цитата: Соловьеву или Гитлеру.</p>
        <Button onClick={() => console.log('bitch')} text='Начать' />
      </main>
      <section>
        <QuizOption />
      </section>
    </>
  )
}

function Button(props: any) {
  return (
    <button style={props.style} className={styles.devuiButton} onClick={props.onClick}>{props.text}</button>
  )
}